export const tabs = [
  { id: "dictionary", label: "Dictionary" },
  { id: "chat", label: "Language Chatbot" },
  { id: "talk", label: "Two-Way Communication" },
  { id: "map", label: "SEA Map" },
  { id: "quiz", label: "Quiz" },
];

export const QUIZ_LANGUAGES = [
  { name: "Khmer",       flag: "🇰🇭­" },
  { name: "Kuy",         flag: "🇰🇭­" },
  { name: "Minangkabau", flag: "🇮🇩" },
  { name: "Jawa",        flag: "🇮🇩" },
  { name: "Sunda",       flag: "🇮🇩" },
  { name: "Shan",        flag: "🇲🇲" },
  { name: "Karen",       flag: "🇲🇲" },
  { name: "Lao",         flag: "🇱🇦" },
  { name: "Hmong",       flag: "🇱🇦" },
  { name: "Lanna",       flag: "🇹🇭" },
  { name: "Isan",        flag: "🇹🇭" },
  { name: "Khmer Krom",  flag: "🇹🇭" },
  { name: "Tay",         flag: "🇻🇳" },
  { name: "Cham",        flag: "🇻🇳" },
  { name: "Khmer Krom",  flag: "🇻🇳" },
  { name: "Cebuano",     flag: "🇵🇭" },
  { name: "Ilocano",     flag: "🇵🇭" },
  { name: "Iban",        flag: "🇲🇾" },
  { name: "Kadazan-Dusun", flag: "🇲🇾" },
  { name: "Teochew",     flag: "🇸🇬" },
  { name: "Hokkien",     flag: "🇸🇬" },
  { name: "Dusun",       flag: "🇧🇳" },
  { name: "Tutong",      flag: "🇧🇳" },
  { name: "Tetum",       flag: "🇹🇱" },
  { name: "Mambae",      flag: "🇹🇱" },
];

// Dictionary languages - synchronized with QUIZ_LANGUAGES (24 regional languages)
export const DICTIONARY_LANGUAGES = [
  { name: "Khmer", code: "km" },
  { name: "Kuy", code: "kuy" },
  { name: "Minangkabau", code: "min" },
  { name: "Jawa", code: "jv" },
  { name: "Sunda", code: "su" },
  { name: "Shan", code: "shn" },
  { name: "Karen", code: "kar" },
  { name: "Lao", code: "lo" },
  { name: "Hmong", code: "hmn" },
  { name: "Lanna", code: "noi" },
  { name: "Isan", code: "tts" },
  { name: "Tay", code: "tyz" },
  { name: "Cham", code: "cjm" },
  { name: "Khmer Krom", code: "kkr" },
  { name: "Cebuano", code: "ceb" },
  { name: "Ilocano", code: "ilo" },
  { name: "Iban", code: "iba" },
  { name: "Kadazan-Dusun", code: "dtp" },
  { name: "Teochew", code: "zh-teo" },
  { name: "Hokkien", code: "zh-hok" },
  { name: "Dusun", code: "dsk" },
  { name: "Tutong", code: "ttg" },
  { name: "Tetum", code: "tet" },
  { name: "Mambae", code: "mgm" },
];

export const COUNTRY_FLAGS = {
  "Cambodia": "🇰🇭­",
  "Myanmar": "🇲🇲",
  "Laos": "🇱🇦",
  "Thailand": "🇹🇭",
  "Vietnam": "🇻🇳",
  "Philippines": "🇵🇭",
  "Malaysia": "🇲🇾",
  "Singapore": "🇸🇬",
  "Brunei": "🇧🇳",
  "Indonesia": "🇮🇩",
  "Timor Leste": "🇹🇱",
};

export const seaCountries = [
  { id: "shan",         name: "Shan",          country: "Myanmar",      top: 22, left: 19, languages: ["Shan"] },
  { id: "karen",        name: "Karen",         country: "Myanmar",      top: 30, left: 16, languages: ["Karen"] },
  { id: "lao",          name: "Lao",           country: "Laos",         top: 30, left: 26, languages: ["Lao"] },
  { id: "hmong",        name: "Hmong",         country: "Laos",         top: 38, left: 33, languages: ["Hmong"] },
  { id: "lanna",        name: "Lanna",         country: "Thailand",     top: 35, left: 22, languages: ["Lanna"] },
  { id: "isan",         name: "Isan",          country: "Thailand",     top: 40, left: 25, languages: ["Isan"] },
  { id: "khmer",        name: "Khmer",         country: "Cambodia",     top: 45, left: 32, languages: ["Khmer"] },
  { id: "kuy",          name: "Kuy",           country: "Cambodia",     top: 43, left: 28, languages: ["Kuy"] },
  { id: "tay",          name: "Tay",           country: "Vietnam",      top: 25, left: 30, languages: ["Tay"] },
  { id: "cham",         name: "Cham",          country: "Vietnam",      top: 43, left: 36, languages: ["Cham"] },
  { id: "khmer_krom",   name: "Khmer Krom",    country: "Vietnam",      top: 48, left: 33, languages: ["Khmer Krom"] },
  { id: "ilocano",      name: "Ilocano",       country: "Philippines",  top: 35, left: 58, languages: ["Ilocano"] },
  { id: "cebuano",      name: "Cebuano",       country: "Philippines",  top: 46, left: 58, languages: ["Cebuano"] },
  { id: "iban",         name: "Iban",          country: "Malaysia",     top: 63, left: 26, languages: ["Iban"] },
  { id: "kadazandusun", name: "Kadazan-Dusun", country: "Malaysia",     top: 59, left: 23, languages: ["Kadazan-Dusun"] },
  { id: "teochew",      name: "Teochew",       country: "Singapore",    top: 66, left: 28, languages: ["Teochew"] },
  { id: "hokkien",      name: "Hokkien",       country: "Singapore",    top: 68, left: 30, languages: ["Hokkien"] },
  { id: "dusun",        name: "Dusun",         country: "Brunei",       top: 60, left: 45, languages: ["Dusun"] },
  { id: "tutong",       name: "Tutong",        country: "Brunei",       top: 62, left: 47, languages: ["Tutong"] },
  { id: "minangkabau",  name: "Minangkabau",   country: "Indonesia",    top: 72, left: 23, languages: ["Minangkabau"] },
  { id: "sunda",        name: "Sunda",         country: "Indonesia",    top: 82, left: 33, languages: ["Sunda"] },
  { id: "jawa",         name: "Javanese",      country: "Indonesia",    top: 84, left: 38, languages: ["Jawa"] },
  { id: "tetum",        name: "Tetum",         country: "Timor Leste",  top: 89, left: 63, languages: ["Tetum"] },
  { id: "mambae",       name: "Mambae",        country: "Timor Leste",  top: 87, left: 66, languages: ["Mambae"] },
];

export const languageOptions = [
  "Indonesia",
  "English",
  "Mandarin",
  "Thai",
  "Vietnamese",
  "Malay",
  "Tagalog",
  "Khmer",
  "Kuy",
  "Minang",
  "Jawa",
  "Sunda",
  "Shan",
  "Karen",
  "Lao",
  "Hmong",
  "Isan",
  "Lanna",
  "Tay",
  "Khmer Krom",
  "Cham",
  "Cebuano",
  "Ilocano",
  "Iban",
  "Kadazan-Dusun",
  "Teochew",
  "Hokkien",
  "Dusun",
  "Tutong",
  "Tetum",
  "Mambae",
];

// Group QUIZ_LANGUAGES by country for quiz UI
export const QUIZ_COUNTRIES = [
  {
    code: "kh",
    name: "Cambodia",
    flag: "🇰🇭",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Cambodia"] && l.flag === COUNTRY_FLAGS["Cambodia"]),
  },
  {
    code: "mm",
    name: "Myanmar",
    flag: "🇲🇲",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Myanmar"] && l.flag === COUNTRY_FLAGS["Myanmar"]),
  },
  {
    code: "la",
    name: "Laos",
    flag: "🇱🇦",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Laos"] && l.flag === COUNTRY_FLAGS["Laos"]),
  },
  {
    code: "th",
    name: "Thailand",
    flag: "🇹🇭",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Thailand"] && l.flag === COUNTRY_FLAGS["Thailand"]),
  },
  {
    code: "vn",
    name: "Vietnam",
    flag: "🇻🇳",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Vietnam"] && l.flag === COUNTRY_FLAGS["Vietnam"]),
  },
  {
    code: "ph",
    name: "Philippines",
    flag: "🇵🇭",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Philippines"] && l.flag === COUNTRY_FLAGS["Philippines"]),
  },
  {
    code: "my",
    name: "Malaysia",
    flag: "🇲🇾",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Malaysia"] && l.flag === COUNTRY_FLAGS["Malaysia"]),
  },
  {
    code: "sg",
    name: "Singapore",
    flag: "🇸🇬",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Singapore"] && l.flag === COUNTRY_FLAGS["Singapore"]),
  },
  {
    code: "bn",
    name: "Brunei",
    flag: "🇧🇳",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Brunei"] && l.flag === COUNTRY_FLAGS["Brunei"]),
  },
  {
    code: "id",
    name: "Indonesia",
    flag: "🇮🇩",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Indonesia"] && l.flag === COUNTRY_FLAGS["Indonesia"]),
  },
  {
    code: "tl",
    name: "Timor Leste",
    flag: "🇹🇱",
    languages: QUIZ_LANGUAGES.filter((l) => COUNTRY_FLAGS["Timor Leste"] && l.flag === COUNTRY_FLAGS["Timor Leste"]),
  },
];
